name: Tests

on: push

jobs:

  with-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: label
        with:
          image: library/nginx:latest # random image with a label
          label: maintainer
      - run: echo "${{ steps.label.outputs.value }}"

  without-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: label
        with:
          image: library/nginx
          label: maintainer
      - run: echo "${{ steps.label.outputs.value }}"